services:
  db_app:
    container_name: db_${PROJECT_NAME}
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PGSQL_DATABASE}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
    volumes:
      - "./shared/db/data:/var/lib/postgresql/data"
      - "./shared/db/backup:/home:rw"
    networks:
      - default 
    restart: always  
  telebot:
    build: ./
    container_name: telebot_${PROJECT_NAME}
    command: python3 ./OlyaTrainingBot.py
    networks:
      - default 
    depends_on:
      - db_app
    restart: always 
  nginx:
    container_name: nginx_${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: sh -c "nginx -g 'daemon off;'"
    ports:
      - ${NGINX_PORT_UP}:${NGINX_PORT_DOWN}
    networks:
      - default 
    depends_on:
      - db_app   
  pgadmin:
    container_name: pga_${PROJECT_NAME}
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./shared/pgadmin:/var/lib/pgadmin"  
    networks:
      - default
    restart: always
 
    